config/routes.rb
Rails.application.routes.draw do
  
  resources :conferences
  resources :surveys
  resources :songs
  resources :projects
  resources :users
  resources :products

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_one :producer, dependent: :destroy
  belongs_to :song

  validates :name, uniqueness: true
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_one :speaker, dependent: :destroy
  validates :name, uniqueness: true
end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  belongs_to :task
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user

  validates :address, uniqueness: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :project
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  belongs_to :speaker
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :artist

  validates :name, :studio, uniqueness: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :twitter_name, :github_name, uniqueness: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :contributors, class_name: 'Person'
  belongs_to :owner, class_name: 'Person'

  validates :name, uniqueness: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_one :artist, dependent: :destroy

  validates :title, uniqueness: true
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  has_many :presentations, dependent: :destroy
  belongs_to :conference
  validates :name, uniqueness: true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, dependent: :destroy

  validates :name, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_one :deliverable, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  act_as_gendered
  has_one :email, dependent: :destroy
  has_one :profile, dependent: :destroy

  validates :name, uniqueness: true
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]
  before_action :create_new_form, only: [:new, :create]
  before_action :create_edit_form, only: [:edit, :update]

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end

  # GET /conferences/new
  def new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference_form.submit(conference_params)

    respond_to do |format|
      if @conference_form.save
        format.html { redirect_to @conference_form, notice: "Conference: #{@conference_form.name} was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    @conference_form.submit(conference_params)

    respond_to do |format|
      if @conference_form.save
        format.html { redirect_to @conference_form, notice: "Conference: #{@conference_form.name} was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    name = @conference.name

    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url, notice: "Conference: #{name} was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    def create_new_form
      conference = Conference.new
      @conference_form = ConferenceForm.new(conference)
    end

    def create_edit_form
      @conference_form = ConferenceForm.new(@conference)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :city, speaker_attributes: [:id, :name, :occupation, 
        presentations_attributes: [:id, :_destroy, :topic, :duration]])
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conferences/_form.html.erb
<%= form_for @conference_form do |f| %>
  <% if @conference_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference_form.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Conference Details</h2>
  <div class="field">
    <%= f.label :name, "Conference Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <h2>Speaker Details</h2>
  <%= f.fields_for :speaker do |speaker_fields| %>
    <%= render "speaker", :f => speaker_fields %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/_presentations.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>

  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>  

  <%= link_to_remove_fields("Delete", f) %>

  <hr />
</div>

app/views/conferences/_speaker.html.erb
<div class="field">
  <%= f.label :name, "Speaker Name" %><br>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :occupation %><br>
  <%= f.text_field :occupation %>
</div>

<h2>Presentantions</h2>
<%= f.fields_for :presentations do |presentations_fields| %>
  <%= render "presentations", :f => presentations_fields %>
<% end %>

<%= link_to_add_fields("Add a Presentation", f, :presentations) %>

app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1>Listing conferences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= conference.name %></td>
        <td><%= conference.city %></td>
        <td><%= link_to 'Show', conference %></td>
        <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference', new_conference_path %>

app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<p>
  <strong>Conference Name:</strong>
  <%= @conference.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @conference.city %>
</p>

<p>
  <strong>Speaker Name:</strong>
  <%= @conference.speaker.name %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @conference.speaker.occupation %>
</p>

<% @conference.speaker.presentations.each do |presentation| %>
  <p>
    <strong>Topic:</strong>
    <%= presentation.topic %>
  </p>
  <p>
    <strong>Duration:</strong>
    <%= presentation.duration %>
  </p>
<% end %>

<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>