config/routes.rb
Rails.application.routes.draw do
  
  resources :conferences
  resources :surveys
  resources :songs
  resources :projects
  resources :users
  resources :products

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_one :producer, dependent: :destroy
  belongs_to :song

  validates :name, uniqueness: true
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_one :speaker, dependent: :destroy
  validates :name, uniqueness: true
end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  belongs_to :task
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user

  validates :address, uniqueness: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :project
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  belongs_to :speaker
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :artist

  validates :name, :studio, uniqueness: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :twitter_name, :github_name, uniqueness: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :contributors, class_name: 'Person'
  belongs_to :owner, class_name: 'Person'

  validates :name, uniqueness: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_one :artist, dependent: :destroy

  validates :title, uniqueness: true
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  has_many :presentations, dependent: :destroy
  belongs_to :conference
  validates :name, uniqueness: true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, dependent: :destroy

  validates :name, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_one :deliverable, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  act_as_gendered
  has_one :email, dependent: :destroy
  has_one :profile, dependent: :destroy

  validates :name, uniqueness: true
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :create_new_form, only: [:new, :create]
  before_action :create_edit_form, only: [:edit, :update]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey_form.submit(survey_params)

    respond_to do |format|
      if @survey_form.save
        format.html { redirect_to @survey_form, notice: "Survey: #{@survey_form.name} was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    @survey_form.submit(survey_params)

    respond_to do |format|
      if @survey_form.save
        format.html { redirect_to @survey_form, notice: "Survey: #{@survey_form.name} was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    name = @survey.name

    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey: #{name} was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    def create_new_form
      survey = Survey.new
      @survey_form = SurveyForm.new(survey)
    end

    def create_edit_form
      @survey_form = SurveyForm.new(@survey)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, questions_attributes: [:id, :_destroy, :content,
        answers_attributes: [:id, :_destroy, :content]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f, options = {})
    html_options = {}
    is_existing = f.object.persisted?
    
    classes = []
    classes << "remove_fields"
    classes << (is_existing ? 'existing' : 'dynamic')
    html_options[:class] = [classes.join(' ')]

    if is_existing
      f.hidden_field(:_destroy) + link_to(name, '#', html_options)
    else
      link_to(name, '#', html_options)
    end
  end

  def link_to_add_fields(name, f, association, options = {})
    new_object = f.object.get_model(association)
    assoc = association.to_s.singularize
    
    fields = f.fields_for(association, new_object, :child_index => "new_#{assoc}") do |builder|
      render(association.to_s, :f => builder)
    end

    html_options = {}
    html_options[:class] = "add_fields"
    html_options[:'data-association'] = assoc
    html_options[:'data-association-insertion-template'] = CGI.escapeHTML(fields).html_safe

    link_to(name, '#', html_options)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/surveys/_answers.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :content, "Answer" %><br>
    <%= f.text_field :content, :size => 40 %>
  </div>

  <%= link_to_remove_fields "Delete", f %>
</div>

app/views/surveys/_form.html.erb
<%= form_for @survey_form do |f| %>
  <% if @survey_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey_form.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :size => 40 %>
  </div>

  <h2>Questions</h2>
  <%= f.fields_for :questions do |question_fields| %>
    <%= render "questions", :f => question_fields %>
  <% end %>

  <%= link_to_add_fields("Add a Question", f, :questions) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_questions.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :content, "Question" %><br>
    <%= link_to_remove_fields "remove", f %><br />
    <%= f.text_area :content, :cols => 30, :rows => 2 %>
  </div>

  <h2>Answers</h2>
  <%= f.fields_for :answers do |answer_fields| %>
    <%= render "answers", :f => answer_fields %>
  <% end %>

  <%= link_to_add_fields "Add Answer", f, :answers %>
  
</div>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1>Listing surveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @survey.name %>
</p>

<h2>Questions</h2>
<% @survey.questions.each do |question| %>
  <p>
    <strong>Question:</strong>
    <%= question.content %>
  </p>

  <% question.answers.each do |answer| %>
    <p>
      <strong>Answer:</strong>
      <%= answer.content %>
    </p>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>